# Generated by Django 5.2.17 on 2026-09-28 06:48

import backend.apps.sharing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        choices=[
                            ("avatar-01", "avatar-01"),
                            ("avatar-02", "avatar-02"),
                            ("avatar-03", "avatar-03"),
                            ("avatar-04", "avatar-04"),
                            ("avatar-05", "avatar-05"),
                            ("avatar-06", "avatar-06"),
                            ("avatar-07", "avatar-07"),
                            ("avatar-08", "avatar-08"),
                        ],
                        default=backend.apps.sharing.models.random_avatar,
                        max_length=9,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "avatar__in",
                                (
                                    "avatar-01",
                                    "avatar-02",
                                    "avatar-03",
                                    "avatar-04",
                                    "avatar-05",
                                    "avatar-06",
                                    "avatar-07",
                                    "avatar-08",
                                ),
                            )
                        ),
                        name="sharing_valid_avatar",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SharingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待同意"),
                            ("accepted", "已同意"),
                            ("rejected", "已拒绝"),
                            ("revoked", "已解除"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "higher_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_higher_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lower_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_lower_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_sent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="sharing_sha_sender__c79f17_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="sharing_sha_recipie_d9b1f3_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lower_user__lt", models.F("higher_user"))),
                        name="sharing_pair_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("recipient", models.F("higher_user")),
                                ("sender", models.F("lower_user")),
                            ),
                            models.Q(
                                ("recipient", models.F("lower_user")),
                                ("sender", models.F("higher_user")),
                            ),
                            _connector="OR",
                        ),
                        name="sharing_pair_members",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ("pending", "accepted", "rejected", "revoked"),
                            )
                        ),
                        name="sharing_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("responded_at__isnull", True), ("status", "pending")
                            ),
                            models.Q(
                                models.Q(("status", "pending"), _negated=True),
                                ("responded_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="sharing_response_time",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("pending", "accepted"))),
                        fields=("lower_user", "higher_user"),
                        name="sharing_one_live_pair",
                    ),
                ],
            },
        ),
    ]
