# Generated by Django 5.2.17 on 2026-09-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("position_name", models.CharField(max_length=200)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("applied", "已投递"),
                            ("in_progress", "流程中"),
                            ("offer", "已录用"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已放弃"),
                        ],
                        default="applied",
                        max_length=30,
                    ),
                ),
                ("application_time", models.DateTimeField(blank=True, null=True)),
                ("ai_interview_time", models.DateTimeField(blank=True, null=True)),
                ("written_test_time", models.DateTimeField(blank=True, null=True)),
                ("first_interview_time", models.DateTimeField(blank=True, null=True)),
                ("second_interview_time", models.DateTimeField(blank=True, null=True)),
                ("third_interview_time", models.DateTimeField(blank=True, null=True)),
                ("hr_interview_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_applications",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="job_applica_user_id_9678d6_idx",
                    ),
                    models.Index(
                        fields=["user", "application_status"],
                        name="job_applica_user_id_447268_idx",
                    ),
                    models.Index(
                        fields=["user", "company_name"],
                        name="job_applica_user_id_665b73_idx",
                    ),
                ],
            },
        ),
    ]
