# Generated by Django 5.2.17 on 2026-09-29 08:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def aggregate_legacy(apps, schema_editor):
    Company = apps.get_model("applications", "JobApplication")
    Position = apps.get_model("applications", "ApplicationPosition")
    Interview = apps.get_model("applications", "PositionInterview")
    Stage = apps.get_model("applications", "SharedStage")
    alias = schema_editor.connection.alias
    groups = {}
    for row in Company.objects.using(alias).order_by("id"):
        groups.setdefault((row.user_id, row.company_name.strip().lower()), []).append(row)
    conflicts = 0
    merged = 0
    for rows in groups.values():
        company = rows[0]
        for row in rows:
            position = Position.objects.using(alias).create(company_id=company.pk, **{field: getattr(row, field) for field in ("position_name", "application_status", "application_time", "application_url", "notes")})
            for kind, name in (("first_interview", "一面"), ("second_interview", "二面"), ("third_interview", "三面"), ("hr_interview", "HR 面")):
                when = getattr(row, kind + "_time")
                if when is not None:
                    Interview.objects.using(alias).create(position_id=position.pk, name=name, scheduled_at=when, duration_minutes=getattr(row, kind + "_duration_minutes") or 60)
        values = {}
        for kind in ("ai_interview", "assessment", "written_test"):
            candidates = [row for row in rows if kind != "assessment" and getattr(row, kind + "_time") is not None]
            chosen = min(candidates, key=lambda row: (getattr(row, kind + "_time"), row.pk)) if candidates else None
            conflicts += max(0, len({getattr(row, kind + "_time") for row in candidates}) - 1)
            when = getattr(chosen, kind + "_time") if chosen else None
            duration = (getattr(chosen, kind + "_duration_minutes") or 60) if chosen else None
            Stage.objects.using(alias).create(company_id=company.pk, type=kind, scheduled_at=when, duration_minutes=duration)
            if kind != "assessment":
                values[kind + "_time"] = when
                values[kind + "_duration_minutes"] = duration
        Company.objects.using(alias).filter(pk=company.pk).update(company_name=company.company_name.strip(), flow_version=2, created_at=min(row.created_at for row in rows), updated_at=max(row.updated_at for row in rows), **values)
        Company.objects.using(alias).filter(pk__in=[row.pk for row in rows[1:]]).delete()
        merged += len(rows) - 1
    print(f"APP-009 migration: companies={len(groups)} merged_rows={merged} shared_time_conflicts={conflicts}; earliest timestamp wins (id breaks ties).")


def reverse_empty_only(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ("ApplicationPosition", "PositionInterview", "SharedStage"):
        if apps.get_model("applications", name).objects.using(alias).exists():
            raise IrreversibleError("APP-009 nested data cannot be represented losslessly by the legacy schema; restore the pre-migration database backup instead.")


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_jobapplication_stage_durations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_name", models.CharField(max_length=200)),
                (
                    "application_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("applied", "已投递"),
                            ("in_progress", "流程中"),
                            ("offer", "已录用"),
                            ("rejected", "已拒绝"),
                            ("withdrawn", "已放弃"),
                        ],
                        default="applied",
                        max_length=30,
                    ),
                ),
                ("application_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PositionInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SharedStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ai_interview", "ai_interview"),
                            ("assessment", "assessment"),
                            ("written_test", "written_test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="flow_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="applicationposition",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="applications.jobapplication",
            ),
        ),
        migrations.AddField(
            model_name="positioninterview",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="applications.applicationposition",
            ),
        ),
        migrations.AddField(
            model_name="sharedstage",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_stages",
                to="applications.jobapplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedstage",
            constraint=models.UniqueConstraint(
                fields=("company", "type"), name="application_unique_shared_stage"
            ),
        ),
        migrations.RunPython(aggregate_legacy, reverse_empty_only),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(models.F("user"), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("company_name")), name="application_unique_company"),
        ),
    ]
